In [1]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C"
2: Setting LC_TIME failed, using "C"
3: Setting LC_MESSAGES failed, using "C"
4: Setting LC_MONETARY failed, using "C"

In [2]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
%%R

require(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Loading required package: tidyverse

In [6]:
# show all columns in the dataframe

pd.set_option('display.max_columns', None)

In [4]:
df_cb = pd.read_csv('merged_CB_smoke_data.csv')
df_cb

,code,name,income,poverty,age_med,population,Tobacco Retail Dealer Cap,Active Tobacco Retail Dealer Licenses,TRD Available Under Cap,Electronic Cigarette Retail Dealer Cap,Active Electronic Cigarette Retail Dealer Licenses,ECD Available Under Cap,activer per 1000
0,2,Manhattan 5&6,142767,9.0,37.6,183089,223,252,0,126,171,0,1.376380
1,2,Manhattan 1&2,159292,8.5,49.5,149102,141,172,0,82,107,0,1.153573
2,2,Manhattan 4,110114,15.4,44.5,112582,97,121,0,58,86,0,1.074772
3,3,Brooklyn 4,90757,19.9,46.1,94423,80,71,9,24,24,0,0.751935
4,4,Queens 5,86150,11.3,32.3,175992,99,132,0,35,49,0,0.750034
5,4,Queens 1,81167,16.1,41.6,177115,106,131,0,46,65,0,0.739632
6,2,Manhattan 3,56386,26.0,42.7,141787,89,96,0,56,67,0,0.677072
7,4,Queens 2,81167,11.5,38.3,125926,70,85,0,26,41,0,0.675000
8,3,Brooklyn 10,81305,12.5,34.8,116696,62,76,0,27,33,0,0.651265
9,5,Staten Island 1,81246,15.0,40.9,184556,99,110,0,34,54,0,0.596025
10,1,Bronx 7,23874,28.6,43.2,132380,63,78,0,18,12,6,0.589213
11,3,Brooklyn 1,95111,18.8,37.9,186944,114,108,6,53,58,0,0.577713
12,3,Brooklyn 6,156437,9.3,38.8,107930,48,61,0,26,38,0,0.565181
13,4,Queens 9,81823,11.5,44.6,136313,60,74,0,24,26,0,0.542868
14,4,Queens 4,64028,17.9,34.2,160534,64,87,0,18,25,0,0.541941
15,1,Bronx 3&6,31120,38.4,36.2,168992,103,91,12,15,16,2,0.538487
16,1,Bronx 4,42963,34.6,45.3,139747,88,75,13,9,5,4,0.536684
17,4,Queens 10,94153,9.1,48.2,129072,47,68,0,21,34,0,0.526838
18,1,Bronx 11,61668,17.6,43.5,114874,55,60,0,19,22,0,0.522311
19,1,Bronx 1&2,31651,32.8,41.6,146382,99,75,24,18,15,3,0.512358
20,1,Bronx 5,32049,38.0,41.0,114828,68,57,11,14,14,0,0.496395
21,3,Brooklyn 7,83202,20.7,49.6,129890,64,64,0,13,14,0,0.492725
22,3,Brooklyn 11,59214,19.5,42.1,184415,87,89,0,31,32,0,0.482607
23,1,Bronx 10,61426,18.9,36.6,136930,52,65,0,30,37,0,0.474695
24,4,Queens 3,77503,15.6,35.3,162686,64,75,0,20,30,0,0.461011
25,2,Manhattan 8,143047,7.2,31.7,206975,74,93,0,39,54,0,0.449330
26,3,Brooklyn 3,71123,24.8,32.4,166380,97,73,24,20,22,0,0.438755
27,2,Manhattan 11,35570,38.2,47.7,128317,62,54,8,14,17,0,0.420833
28,3,Brooklyn 2,131217,12.9,37.7,135987,64,57,7,25,28,0,0.419158
29,1,Bronx 12,60483,26.0,35.9,153790,66,64,2,21,28,0,0.416152
30,4,Queens 12,72397,13.4,48.8,248158,118,103,15,23,26,0,0.415058
31,1,Bronx 8,76271,10.6,41.0,87280,36,36,0,12,12,0,0.412466
32,5,Staten Island 2,91734,9.6,48.8,145506,50,59,0,34,53,0,0.405482
33,3,Brooklyn 15,61037,19.1,43.8,151970,59,61,0,32,34,0,0.401395
34,4,Queens 6,90502,10.6,51.0,128592,35,51,0,19,32,0,0.396603
35,4,Queens 7,70508,16.0,43.1,246851,71,97,0,31,51,0,0.392950
36,2,Manhattan 10,50079,28.2,29.7,138953,62,54,8,13,8,5,0.388621
37,5,Staten Island 3,108376,7.8,42.8,161071,42,61,0,32,53,0,0.378715
38,4,Queens 8,78087,11.8,46.6,148045,38,55,0,21,39,0,0.371509
39,4,Queens 14,64280,17.6,40.7,126629,37,45,0,10,13,0,0.355369
40,3,Brooklyn 18,84272,11.5,42.6,189888,55,65,0,21,27,0,0.342307
41,2,Manhattan 9,59472,24.2,47.9,105801,42,36,6,16,20,0,0.340261
42,3,Brooklyn 9,77119,17.0,37.1,94109,39,32,7,10,11,0,0.340031
43,3,Brooklyn 17,70874,17.8,35.3,160620,59,54,5,9,13,0,0.336197
44,3,Brooklyn 14,71351,21.3,39.6,152340,57,51,6,21,27,0,0.334777
45,3,Brooklyn 8,78598,20.2,40.5,107419,46,33,13,12,12,0,0.307208
46,4,Queens 11,99269,8.4,47.9,118293,28,36,0,15,22,0,0.304329
47,3,Brooklyn 12,66061,23.8,36.9,191368,49,58,0,16,23,0,0.303081
48,3,Brooklyn 16,35431,39.1,35.1,99827,48,30,18,6,5,1,0.300520
49,2,Manhattan 7,140255,10.5,37.2,226989,61,68,0,33,45,0,0.299574
50,3,Brooklyn 5,54431,24.6,40.7,200828,94,60,34,15,11,4,0.298763
51,2,Manhattan 12,59898,20.1,39.6,202678,86,60,26,28,25,3,0.296036
52,1,Bronx 9,46904,23.7,42.6,184743,78,54,24,15,15,0,0.292298
53,4,Queens 13,101052,8.7,45.1,193823,54,56,0,19,24,0,0.288923
54,3,Brooklyn 13,43146,24.9,38.4,119482,30,28,2,18,27,0,0.234345

In [5]:
df_city_license = pd.read_csv('Active_Tobacco_Retail_Dealer_Licenses_20240425.csv')
df_city_license

,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Address Building,Address Street Name,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
0,1178405-DCA,Business,12/31/2023,Active,08/27/2004,Tobacco Retail Dealer,OLSEN NEWS CORP.,NaN,NaN,BROADWAY,...,105.0,3.0,NaN,NaN,NaN,NaN,NaN,-73.986865,40.754317,"(40.75431708865135, -73.98686541972873)"
1,2016212-1-DCA,Business,12/31/2023,Active,12/05/2014,Tobacco Retail Dealer,ASTORIA CENTER INC,NaN,4402,ASTORIA BLVD,...,401.0,22.0,4012858.0,4.007170e+09,QN70,141.0,NaN,-73.906927,40.768202,"(40.76820158202948, -73.9069268281986)"
2,1217359-DCA,Business,12/31/2023,Active,01/11/2006,Tobacco Retail Dealer,"FLEUR, RONY ST",RON'S DELI GROCERY STORE,17024,JAMAICA AVE,...,412.0,27.0,4217486.0,4.102120e+09,QN61,444.0,NaN,-73.789284,40.707291,"(40.70729121951161, -73.7892842185725)"
3,1435239-DCA,Business,12/31/2023,Active,06/22/2012,Tobacco Retail Dealer,PRESBYTERIAN 164 DELI CORP.,NaN,1081,SAINT NICHOLAS AVE,...,112.0,7.0,1062937.0,1.021220e+09,MN36,245.0,NaN,-73.940020,40.837602,"(40.83760200533997, -73.94001991132355)"
4,2045066-1-DCA,Business,12/31/2023,Active,10/26/2016,Tobacco Retail Dealer,A & M DELI & GRILL INC,NaN,13202,JAMAICA AVE,...,409.0,29.0,4196340.0,4.093400e+09,QN54,14202.0,NaN,-73.820497,40.702110,"(40.70210984823282, -73.82049747055868)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4375,2115065-2-DCA,Business,12/31/2024,Active,07/13/2023,Tobacco Retail Dealer,BRUCKNER EXPRESSWAY INC.,NaN,1419,BRUCKNER BLVD,...,209.0,17.0,2023319.0,2.037080e+09,NaN,NaN,NaN,-73.882953,40.823223,"(40.82322255964534, -73.88295261067725)"
4376,1428271-DCA,Business,12/31/2023,Active,05/07/2012,Tobacco Retail Dealer,"FAMILY DOLLAR STORES OF NEW YORK, INC.",FAMILY DOLLAR #6368,887,E NEW YORK AVE,...,309.0,41.0,3331592.0,3.014300e+09,BK60,880.0,NaN,-73.933365,40.662651,"(40.66265090040348, -73.93336484600341)"
4377,2115058-2-DCA,Business,12/31/2024,Active,07/13/2023,Tobacco Retail Dealer,"JUNIORS GOURMET DELI, JUICE BAR, & SMOKE SHOP ...",NaN,1181,BEDFORD AVE,...,303.0,36.0,3329696.0,3.018270e+09,NaN,NaN,NaN,-73.953835,40.683024,"(40.6830244295472, -73.95383474133375)"
4378,2013634-1-DCA,Business,12/31/2023,Active,09/18/2014,Tobacco Retail Dealer,TRIDEV PETROLEUM INC,GULF,755,PENNSYLVANIA AVE,...,305.0,42.0,3097326.0,3.043230e+09,BK82,1104.0,NaN,-73.891155,40.659270,"(40.65927007183555, -73.89115522506118)"
4379,2016557-1-DCA,Business,12/31/2023,Active,12/16/2014,Tobacco Retail Dealer,MIDDLE EASTERN GROCERY CORP.,NaN,2512,STEINWAY ST,...,401.0,22.0,4010277.0,4.006540e+09,NaN,NaN,NaN,-73.912004,40.767585,"(40.767585259528396, -73.9120035094514)"